### ISSUE TITLE
'ChangeInToContains' only changes in to contains when outside of brackets

### ISSUE THREAD

**Issue by Caeylinity** [NilsSve/DfRefactor#37] opened 2023-10-31 15:11 UTC
`If "stst" in "teststring"` will be changed to `If ("teststring" contains "stst")`, but `If ("stst" in "teststring")` wil remain `If ("stst" in "teststring")`

**Comment by NilsSve** [comment] 2023-11-02 08:49
This is a limitation of the "in" operator. The operator is not valid to be used within an expression. If it does, it will generate a compile error.

As the issue isn't a refactoring issue per se, I will close it.

**Closed by NilsSve** 2023-11-02 08:49 UTC
